name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 7.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.0

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish src/BlazorClient/BlazorClient.csproj -c Release -o release --nologo
    
    # changes the base-tag in index.html from '/' to 'BlazorClient' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to BlazorClient
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorClient\/" \/>/g' release/wwwroot/index.html

    - name: Set ACTIONS_ID_TOKEN_REQUEST_URL
      env:
        ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
    
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.9
